//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtectionProjectManagement.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int id_login { get; set; }
        public string Login1 { get; set; }
        public string Password { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
