//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtectionProjectManagement.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public int AuthorID { get; set; }
        public int PerformerID { get; set; }
        public int ProjectID { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public int Priority { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
